### ISSUE TITLE
 type-only imports for axios

### ISSUE THREAD

**Issue by jclijmans** [RicoSuter/NSwag#3964]
Hello,

I'm using nswag to generate a typescript client for my API using the axios template.
I'm using typescript 4.6 in my project.

The typescript compiler typechecking produces an error for the import of the axios types.

Generated import statement :

`import axios, { AxiosError, AxiosInstance, AxiosRequestConfig, AxiosResponse, CancelToken } from 'axios';
`
Error : 
error TS1444: 'AxiosError' is a type and must be imported using a type-only import when 'preserveValueImports' and 'isolatedModules' are both enabled.

For typescript 4.5 and higher, the generated code should be 

`import axios, { type AxiosInstance, type AxiosRequestConfig, type AxiosResponse, type CancelToken } from 'axios';
`
I cannot change the preserveValueImports or isolatedModules compiler options because they are needed by vite-vue.

How can I generate the type-only imports or can the axios template be updated to include the type-only option?

**Comment by tomvdk** [comment]
@jclijmans I've created PR for this that will solve this issue by allowing type only imports when TypeScript >= 4.3 is selected

**Comment by jclijmans** [comment]
@tomvdk : After updating nswag to version 13.16.0, there still seems to be an error after generating a client for typescript 4.6.3

AxiosError should also be a type-only import

'AxiosError' is a type and must be imported using a type-only import when 'preserveValueImports' and 'isolatedModules' are both enabled.ts(1444)

**Comment by jclijmans** [comment]
Hi @tomvdk, thw for your reply.
I was indeed still on version 0.26.1 of axios. 
After updating the axios version and typescript to 4.7 in the nswag file, the code is correctly generated.

So, I'll close this issue.

**Comment by Kasheftin** [comment]
I've just installed nswag with `npm install nswag -g`. 
I have `tmp/api.json` file.
I run `nswag openapi2tsclient /input:tmp/api.json /output:tmp/api.ts /template:Axios /operationGenerationMode:MultipleClientsFromOperationId`
It generates typescript without type only imports.

**Comment by jclijmans** [comment]
You need to supply the typescript version with your command. For the type-only imports to be generated, the typescript version needs to be 3.8 or higher. By default the typescript version is 2.7.

**Comment by Kasheftin** [comment]
Thank you, it works. The param name is `/typeScriptVersion:3.8`, the full command is `nswag openapi2tsclient /input:tmp/api.json /output:tmp/api.ts /template:Axios /operationGenerationMode:MultipleClientsFromOperationId /typeScriptVersion:3.8`.
