### ISSUE TITLE
Error:  After Update from NSwag v13.11.3.0 to v13.12.1.0

### ISSUE THREAD

**Issue by billpeace** [RicoSuter/NSwag#3570]
service-proxies.ts:9150:9 - error TS2322: Type 'Observable< null>' is not assignable to type 'Observable< string>'.

9150         return _observableOf(null);
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~

service-proxies.ts:7814:9 - error TS2322: Type 'Observable < null>' is not assignable to type 'Observable<SaveColumnDto[]>'. 
  Type 'null' is not assignable to type 'SaveColumnDto[]'.

7814         return _observableOf(null);

**Comment by jeremyVignelles** [comment]
Duplicate of #3568 ?
